### ISSUE TITLE
Publish to the Google Play Store.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [PrivacyDragon/Bookwyrm_Android#11]

**Comment by PrivacyDragon** [comment]
At the moment, I do not have intentions to publish the app to the Google Play Store.
Once an API has been implemented in the Bookwyrm project, I am pretty sure that other people will be able to build much neater Bookwyrm clients.
Plus that I do not really like having to go trough all the hassle of putting it on the Play Store. I would need to create a whole new Google account dedicated to it, providing them with an awful lot of personal information, and all that. If I remember correctly. (I looked into it once.)

So, for now I do not intend to put it up there.
