### ISSUE TITLE
Initial flash screen

### ISSUE THREAD

**Issue by shuvashish76** [PrivacyDragon/Bookwyrm_Android#3]
![Screenshot_2022-04-27-07-46-37](https://user-images.githubusercontent.com/48226312/165425724-4d6ef34b-8461-4e71-9d20-786922cc95da.jpeg)

Change the initial startup flashscreen to black. My Bookwyrm theme is set to Dark so the bright white flash is very annoying.

Android version : 8.1.0
App version : 1.3.1 (8)

**Comment by PrivacyDragon** [comment]
Thanks for reporting!
Fortunately it was an easy fix.
I will release it maybe later today. Or tomorrow.

**Comment by shuvashish76** [comment]
For future reference :
- Fixed with https://github.com/PrivacyDragon/Bookwyrm_Android/commit/8037938adfa988e272453b0e6e3a986e68801b7c

Thanks
