### ISSUE TITLE
Bug - Timestamp of book activities incorrect or changed

### ISSUE THREAD

**Issue by s38b35M5** [PrivacyDragon/Bookwyrm_Android#8]
Several books I have read follow this pattern:

Select book
Click or tap 'start reading' 
Date shows today's date
Days later, click or tap 'finish reading' 
The resulting form has changed the start reading date by a handful of days. Correcting the dates before submitting seems not to fix this issue.

For example, the book I finished last night (https://bookwyrm.social/book/147905/s/the-book-of-three) was started on September 23 (I have the receipt from the ebook purchase on this date) and finished September 30 (last night).

However, Bookwyrm reports the following dates:
Progress Updates:
Sept. 29, 2023: finished 
Sept. 19, 2023: started

This is present in the android app and the mobile and desktop websites.

Dates entered into the system should remain static, in the local timezone, and reflect actual reading timestamps.

![Screenshot_20231001-090947_Bookwyrm](https://github.com/PrivacyDragon/Bookwyrm_Android/assets/138058715/e1940b0b-6dbe-4283-92a7-98fcd1f48c7f)

**Comment by PrivacyDragon** [comment]
This is a bug more for the main Bookwyrm developers.
So try submitting a bug report there.
https://github.com/bookwyrm-social/bookwyrm/issues
